### ISSUE TITLE
代码不全

### ISSUE THREAD

**Issue by xilinniao123** [srtianxia/opinion_mining#1]
感谢分享！第二阶段加载模型更换分类器的代码没有吧？能否补充下

**Comment by srtianxia** [comment]
你好，感谢关注，第二阶段加载模型直接使用 `train_model.load_weights(filename,by_name=True)` 记得将前面的所有层给命名，然后直接更换最后一个`Categories`的`Dense`层，赋予一个新的name，再加载laptop的数据就可以了。
