### ISSUE TITLE
大佬，帮个忙啊

### ISSUE THREAD

**Issue by linyuchuan** [srtianxia/opinion_mining#3]
大佬你好，我这边有一个任务和该比赛的任务基本上差不多。我使用了多任务联合建模来做，效果确实比单个任务训练有比较大的提升。但是该比赛我最近才看到，并没有参加。现在我想在这个比赛的初赛和复赛的数据集上再跑一遍我的模型，看一下联合建模方法和其他人方法的对比。请问能否把复赛的数据发给我一份。我这边可以试一下

**Comment by Ming-Qin-tech** [comment]
请问你拿到这个比赛的数据了吗？我也需要，求支援，谢谢谢谢

**Comment by qm693514099** [comment]
邮箱qinandmig@163.com万分感谢

**Comment by Ming-Qin-tech** [comment]
请问你拿到这个比赛的数据了吗，可以分享一下吗？邮箱qinandming@163.com万分感谢

**Comment by linyuchuan** [comment]
我后来找到了一份，发给你

**Comment by biubiu202012** [comment]
> 我后来找到了一份，发给你

请问复赛数据可以给我发一份吗，找了好久都没找到，邮箱是freyjalin@foxmail.com 谢谢！

**Comment by srtianxia** [comment]
> > 我后来找到了一份，发给你
> 
> 请问复赛数据可以给我发一份吗，找了好久都没找到，邮箱是[freyjalin@foxmail.com](mailto:freyjalin@foxmail.com) 谢谢！

见邮箱。

**Comment by w-zm** [comment]
> 我后来找到了一份，发给你

您好，请问可以发一下这个比赛的数据集给我么？也是找了好多地方都没找到，邮箱是354242964@qq.com，谢谢。

**Comment by milktean** [comment]
> > > 我后来找到了一份，发给你
> > 
> > 
> > 请问复赛数据可以给我发一份吗，找了好久都没找到，邮箱是[freyjalin@foxmail.com](mailto:freyjalin@foxmail.com) 谢谢！
> 
> 见邮箱。

你好，请问这个数据也可以分享给我一份吗，万分感谢。我的邮箱：2640279309@qq.com
